name: sipardy_app
description: A drinking game based on Jeopardy
publish_to: 'none'
version: 1.2.2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Local persistence
  shared_preferences: ^2.5.2

  # Supabase
  supabase_flutter: ^2.8.1

  # State Management
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.7

  # Notifications
  delightful_toast: ^1.1.0

  # Icons
  lucide_icons_flutter: ^1.2.5

  # UI Helpers
  gap: ^3.0.1
  pinput: ^5.0.0
  skeletonizer: ^1.4.2
  flutter_confetti: ^0.3.4
  bitsdojo_window: ^0.1.6

  # Splash
  flutter_native_splash: ^2.4.3

  # General Helpers
  url_launcher: ^6.3.1
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13

  # Generators
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Switzer
      fonts:
        - asset: fonts/Switzer-Black.otf
        - asset: fonts/Switzer-BlackItalic.otf
          style: italic
        - asset: fonts/Switzer-Bold.otf
        - asset: fonts/Switzer-BoldItalic.otf
          style: italic
        - asset: fonts/Switzer-Extrabold.otf
        - asset: fonts/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: fonts/Switzer-Extralight.otf
        - asset: fonts/Switzer-ExtralightItalic.otf
          style: italic
        - asset: fonts/Switzer-Italic.otf
          style: italic
        - asset: fonts/Switzer-Light.otf
        - asset: fonts/Switzer-LightItalic.otf
          style: italic
        - asset: fonts/Switzer-Medium.otf
        - asset: fonts/Switzer-MediumItalic.otf
          style: italic
        - asset: fonts/Switzer-Regular.otf
        - asset: fonts/Switzer-Semibold.otf
        - asset: fonts/Switzer-SemiboldItalic.otf
          style: italic
        - asset: fonts/Switzer-Thin.otf
        - asset: fonts/Switzer-ThinItalic.otf
          style: italic

