-- Add questions for the new catgeory
INSERT INTO public.game_questions (category, points, question, answer) VALUES
('football', 1, 'Wie viele Punkte gibt ein Touchdown?', '6'),
('football', 1, 'Wie viele Spieler stehen pro Team auf dem Feld?', '11'),
('football', 1, 'Wie nennt man den Spieler, der den Ball wirft?', 'Quarterback'),
('football', 1, 'In welcher Liga spielen die besten American-Football-Teams?', 'NFL'),
('football', 1, 'Wie viele Viertel gibt es in einem American-Football-Spiel?', '4'),
('football', 1, 'Wie viele Punkte gibt ein erfolgreiches Field Goal?', '3'),
('football', 1, 'Wie nennt man den Versuch, nach einem Touchdown zwei Extrapunkte zu erzielen?', 'Two-Point Conversion'),
('football', 1, 'Wie nennt man die Spielerposition, die den Ball läuft?', 'Running Back'),
('football', 1, 'Wie heißt das Finale der NFL-Saison?', 'Super Bowl'),
('football', 1, 'Welches Team gewann den Super Bowl 2024?', 'Kansas City Chiefs'),
('football', 1, 'Welches Team hat die meisten Super-Bowl-Titel?', 'New England Patriots & Pittsburgh Steelers'),
('football', 1, 'Wie nennt man die Zone am Ende des Spielfelds, in die ein Touchdown erzielt wird?', 'Endzone'),
('football', 1, 'Wie viele Punkte gibt ein Safety?', '2'),
('football', 1, 'Wie viele Yards hat ein Footballfeld (ohne Endzonen)?', '100'),
('football', 1, 'Wer ist der berühmteste Quarterback der NFL-Geschichte?', 'Tom Brady'),
('football', 1, 'Wie nennt man die Linie, an der der Spielzug beginnt?', 'Line of Scrimmage'),
('football', 1, 'Was bedeutet die Abkürzung "NFL"?', 'National Football League'),
('football', 1, 'Wie viele Yards sind für ein First Down nötig?', '10'),
('football', 1, 'Wie nennt man den Wurf des Quarterbacks nach hinten?', 'Lateral Pass'),
('football', 1, 'Wie nennt man das Spielen mit der Hand an der Line of Scrimmage?', 'Snap'),

('football', 2, 'Wer gewann den ersten Super Bowl?', 'Green Bay Packers'),
('football', 2, 'Wie oft haben die Dallas Cowboys den Super Bowl gewonnen?', '5'),
('football', 2, 'Welche Farbe hat das Heimtrikot der Green Bay Packers?', 'Grün'),
('football', 2, 'Welche Position trägt den Ball meist in die Endzone?', 'Running Back oder Wide Receiver'),
('football', 2, 'Was ist ein "Huddle"?', 'Besprechung der Spieler vor dem Spielzug'),
('football', 2, 'Wie nennt man es, wenn der Quarterback hinter der Line of Scrimmage zu Boden gebracht wird?', 'Sack'),
('football', 2, 'Welche Strafe gibt es für das Festhalten eines Gegners?', 'Holding'),
('football', 2, 'Wie viele Schiedsrichter gibt es normalerweise in einem NFL-Spiel?', '7'),
('football', 2, 'Wer hält den Rekord für die meisten Touchdown-Pässe in der NFL-Geschichte?', 'Tom Brady'),
('football', 2, 'Welche Stadt ist Heimat der Chicago Bears?', 'Chicago'),
('football', 2, 'Wie viele Downs hat ein Team, um ein First Down zu erzielen?', '4'),
('football', 2, 'Wie nennt man den Spieler, der den Ball zum Kicker hält?', 'Holder'),
('football', 2, 'Wie viele Spieler dürfen sich an der Line of Scrimmage befinden?', 'Mindestens 7'),
('football', 2, 'Was bedeutet "Interception"?', 'Ein Pass wird von der Verteidigung abgefangen'),
('football', 2, 'Welches Team trägt goldene Helme mit einem schwarzen Fleur-de-Lis?', 'New Orleans Saints'),
('football', 2, 'Wie nennt man die Gruppe von Spielern, die den Quarterback schützen?', 'Offensive Line'),
('football', 2, 'Wer ist der aktuelle Commissioner der NFL?', 'Roger Goodell'),
('football', 2, 'Wie nennt man einen Pass, der von keinem Spieler gefangen wird?', 'Incomplete Pass'),
('football', 2, 'Was ist eine "Pick-Six"?', 'Interception, die für einen Touchdown zurückgetragen wird'),

('football', 3, 'Wie lang ist das Spielfeld inklusive Endzonen?', '120 Yards'),
('football', 3, 'Wie nennt man einen Pass, der hinter der Line of Scrimmage gefangen wird?', 'Screen Pass'),
('football', 3, 'Wer hält den Rekord für die meisten Rushing Yards in einer Saison?', 'Eric Dickerson'),
('football', 3, 'Wie viele Teams gibt es in der NFL?', '32'),
('football', 3, 'Wie nennt man die Verteidigungstaktik, bei der mehrere Spieler den Quarterback attackieren?', 'Blitz'),
('football', 3, 'Welche zwei Conferences gibt es in der NFL?', 'AFC & NFC'),
('football', 3, 'Was ist eine "Hail Mary"?', 'Ein langer Verzweiflungspass'),
('football', 3, 'Wer hält den Rekord für die meisten gefangenen Touchdowns in einer Saison?', 'Randy Moss'),
('football', 3, 'Wie viele Overtime-Perioden kann es in einem regulären Saisonspiel geben?', '1'),
('football', 3, 'Welche Stadt ist Heimat der Denver Broncos?', 'Denver'),
('football', 3, 'Wer ist der jüngste Quarterback, der einen Super Bowl gewonnen hat?', 'Ben Roethlisberger'),
('football', 3, 'Welche Position deckt normalerweise die Wide Receiver ab?', 'Cornerback'),
('football', 3, 'Wie nennt man es, wenn ein Team absichtlich die Zeit herunterspielt?', 'Clock Management'),
('football', 3, 'Wie viele Spiele hat eine reguläre NFL-Saison?', '17'),
('football', 3, 'Wer ist der Head Coach mit den meisten Super-Bowl-Siegen?', 'Bill Belichick'),
('football', 3, 'Wer wurde am häufigsten als MVP der NFL ausgezeichnet?', 'Peyton Manning'),
('football', 3, 'Wer war der erste nicht-amerikanische NFL-Spieler?', 'Sebastian Janikowski'),
('football', 3, 'Was bedeutet die Strafe "Offside"?', 'Ein Spieler überquert die Line of Scrimmage zu früh'),
('football', 3, 'Wer gewann den Super Bowl im Jahr 2000?', 'St. Louis Rams'),

('football', 4, 'Was ist die maximale Anzahl an Overtime-Perioden in den Playoffs?', 'Unbegrenzt'),
('football', 4, 'Wie viele Spieler wurden als #1 Pick in der NFL Draft Geschichte Quarterbacks?', 'Über 30'),
('football', 4, 'Wer hält den Rekord für die meisten Passing Yards in einer einzigen Saison?', 'Peyton Manning'),
('football', 4, 'Welches Team gewann den Super Bowl ohne einen einzigen Touchdown zu erzielen?', 'New York Giants (Super Bowl XXV)'),
('football', 4, 'Wer war der erste schwarze Quarterback, der einen Super Bowl gewann?', 'Doug Williams'),
('football', 4, 'Wie oft hat Tom Brady den Super Bowl gewonnen?', '7-mal'),
('football', 4, 'Wer war der älteste NFL-Spieler, der je aktiv war?', 'George Blanda (48 Jahre)'),
('football', 4, 'Welche Stadt verlor zwei NFL-Teams?', 'Los Angeles'),
('football', 4, 'Wer war der erste Super-Bowl-MVP?', 'Bart Starr'),
('football', 4, 'Wer war der erste Kicker, der ins Hall of Fame aufgenommen wurde?', 'Jan Stenerud'),
('football', 4, 'Welches Team hält den Rekord für die längste Siegesserie?', 'New England Patriots'),
('football', 4, 'Wie viele Punkte wurden im höchsten Super-Bowl-Sieg erzielt?', '55 (San Francisco 49ers, SB XXIV)'),
('football', 4, 'Welcher Spieler hält den Rekord für die meisten Receiving Yards in einem Spiel?', 'Flipper Anderson'),
('football', 4, 'Welche Regel wurde nach Tom Bradys "Tuck Rule"-Spiel geändert?', 'Tuck Rule wurde abgeschafft'),
('football', 4, 'Wer war der erste deutsche NFL-Spieler?', 'Uwe von Schamann'),
('football', 4, 'Welches Team wurde 2002 neu in die NFL aufgenommen?', 'Houston Texans'),
('football', 4, 'Wer war der erste Head Coach, der fünf Super Bowls gewann?', 'Bill Belichick'),
('football', 4, 'Welches Team hat die meisten Playoff-Siege?', 'New England Patriots'),
('football', 4, 'Wer hatte den längsten Punt der NFL-Geschichte?', 'Steve O''Neal (98 Yards)'),

('football', 5, 'Welcher NFL-Spieler hält den Rekord für die meisten Career-Sacks?', 'Bruce Smith'),
('football', 5, 'Welches Team gewann den einzigen perfekten Super Bowl (ungeschlagene Saison)?', 'Miami Dolphins (1972)'),
('football', 5, 'Welches NFL-Team hat die längste Playoff-Dürre (kein Playoff-Einzug für die meisten Jahre)?', 'New York Jets'),
('football', 5, 'Wer war der erste Spieler, der in vier verschiedenen Jahrzehnten in der NFL spielte?', 'George Blanda'),
('football', 5, 'Welches Team verlor vier Super Bowls in Folge?', 'Buffalo Bills'),
('football', 5, 'Welcher Quarterback warf die meisten Interceptions in einer einzigen NFL-Saison?', 'George Blanda (42)'),
('football', 5, 'Welches Team hat die meisten Overtime-Siege in der NFL-Geschichte?', 'Denver Broncos'),
('football', 5, 'Wer war der erste nicht-amerikanische Quarterback, der in einem Super Bowl startete?', 'Mark Rypien (Kanada)'),
('football', 5, 'Welche NFL-Franchise wurde zuerst gegründet?', 'Arizona Cardinals (als Chicago Cardinals)'),
('football', 5, 'Wer ist der jüngste Spieler, der jemals in der NFL gedraftet wurde?', 'Amobi Okoye (19 Jahre)'),
('football', 5, 'Welches war das erste NFL-Team, das einen schwarzen Head Coach einstellte?', 'Oakland Raiders (Art Shell)'),
('football', 5, 'Welches war das erste Super-Bowl-Team, das während der gesamten Saison keine Rückstände hatte?', 'New England Patriots (2007, aber verloren den Super Bowl)'),
('football', 5, 'Welcher Kicker hält den Rekord für das längste Field Goal in der NFL?', 'Justin Tucker (66 Yards)'),
('football', 5, 'Welcher Running Back hat die meisten Rushing Yards in einem einzigen Spiel erzielt?', 'Adrian Peterson (296 Yards)'),
('football', 5, 'Welche zwei NFL-Teams teilen sich ein Stadion?', 'New York Giants & New York Jets (MetLife Stadium)'),
('football', 5, 'Wer war der letzte nicht-kickende Spieler, der mit der Nummer 00 spielte?', 'Jim Otto'),
('football', 5, 'Welcher Wide Receiver hat die meisten Career-Receptions?', 'Jerry Rice'),
('football', 5, 'Welcher Quarterback hat die meisten 500-Yard-Passing-Spiele in der NFL-Geschichte?', 'Ben Roethlisberger'),
('football', 5, 'Wer war der erste ungedraftete Spieler, der zum NFL MVP gewählt wurde?', 'Kurt Warner'),
('football', 5, 'Welches Team hat die meisten Niederlagen in der NFL-Geschichte?', 'Arizona Cardinals');